# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Speed_OSAR_nbdev',
                'doc_host': 'https://lnicole08.github.io',
                'git_url': 'https://github.com/lnicole08/Speed_OSAR_nbdev',
                'lib_path': 'Speed_OSAR_nbdev'},
  'syms': {}}